### ISSUE TITLE
Sometimes items don't have titles.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-content#80]
Not sure how or why, but sometimes pages that definitely have HTML `<title>` elements aren't having titles handed off to the content:

<img width="642" alt="screen shot 2015-11-23 at 12 48 13 pm" src="https://cloud.githubusercontent.com/assets/23885/11347879/936e70de-91e0-11e5-9c5c-a88b67a576f0.png">

This bug is in two parts:
1. Why is that happening? It shouldn't. https://github.com/mozilla/universal-search-addon/issues/142
2. The iframe should handle it better, in the event that it does happen. (this bug)

_Edited to undo my inaccurate editing, sorry!_

**Comment by chuckharmston** [comment]
@bryanbell for part two, would it make sense to show the URL as if it is the title, and not show the normal blue URL segment at all?

**Comment by chuckharmston** [comment]
@bryanbell How should we handle title-less items with the UI tweaks?

**Comment by chuckharmston** [comment]
We'll use the domain name for a title for now.

**Comment by jaredhirsch** [comment]
It looks like this bug is fixed, here's how similar results look in the add-on today:

<img width="408" alt="screenshot 2016-01-27 13 02 40" src="https://cloud.githubusercontent.com/assets/96396/12628071/479a3898-c4f6-11e5-82bd-cf0fbca948a2.png">

Closing accordingly. Please reopen if I've missed something :-)
